name: Building image with maven
on: push
jobs:
    Clone:
        - name: Cloning repo
          uses: actions/checkout@v3
    Install:
        - name: Install JDK17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            
