name: Building image with maven
on: push
jobs:
    Clone:
      runs-on: ubuntu-latest
      steps:
        - name: Cloning repo
          uses: actions/checkout@v3
    Install:
      runs-on: ubuntu-latest
      steps:
      - name: Install JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
            
